### ISSUE TITLE
Website does not display images

### ISSUE THREAD

**Issue by Pantyhose-X** [thomasrudin-mt/mtinfo#108]
https://pantyhose-x.github.io/Crafting/#/mods/3d_armor/items
https://github.com/Pantyhose-X/Crafting

![55556666](https://user-images.githubusercontent.com/42504385/218506088-4fd25f6f-e299-4537-85d9-00e339561d9c.PNG)
![0666](https://user-images.githubusercontent.com/42504385/218506079-aba64176-ebef-4418-a6b0-435ddaa9f4af.PNG)

**Comment by Pantyhose-X** [comment]
bro @BuckarooBanzay 
I used your latest mtinfo code
You have not solved the site does not display images,
https://pantyhose-x.github.io/Crafting/#/mods/

**Comment by BuckarooBanzay** [comment]
i don't have any idea how your setup and process looks like, i can't really reproduce this without more info (i thought you learned that by now from the various other comments on your pointless issues)

**Comment by Pantyhose-X** [comment]
> i don't have any idea how your setup and process looks like, i can't really reproduce this without more info (i thought you learned that by now from the various other comments on your pointless issues)

process , I uploaded the `minetest-5.6.1-win64\worlds\world1\mtinfo` folder directly to github
